#pragma once
/* Auto-generated by CMake — do not edit. Re-run cmake configure to rotate identities. */

#define DRV_IOCTL_DEVICE_TYPE 0xA466

#define DRV_IOCTL_FUNC_READ        2496
#define DRV_IOCTL_FUNC_MODULE_BASE 2497
#define DRV_IOCTL_FUNC_PING        2498
#define DRV_IOCTL_FUNC_WRITE       2499
#define DRV_IOCTL_FUNC_GET_PEB     2500

#define DRV_PING_MAGIC 0x1A6C51FC3A4A9A6CULL

#define DRV_DEVICE_SUFFIX_W   L"ZcjxhJEaNKSf"
#define DRV_USER_DEVICE_PATH  L"\\\\.\\ZcjxhJEaNKSf"
#define DRV_KERNEL_DRIVER_OBJ L"\\Driver\\ZcjxhJEaNKSf"
#define DRV_KERNEL_DEVICE     L"\\Device\\ZcjxhJEaNKSf"
#define DRV_KERNEL_SYMLINK    L"\\DosDevices\\ZcjxhJEaNKSf"

#define DRV_SYS_FILE_NAME     L"ZcjxhJEaNKSf.sys"
#define DRV_MAPPER_EXE_NAME   L"UsOxYemtJL.exe"
#define DRV_HOST_EXE_NAME     L"KceEcKsbks.exe"
