#pragma once
/* Auto-generated by CMake — do not edit. Re-run cmake configure to rotate identities. */

#define DRV_IOCTL_DEVICE_TYPE 0xFF6D

#define DRV_IOCTL_FUNC_READ        2209
#define DRV_IOCTL_FUNC_MODULE_BASE 2210
#define DRV_IOCTL_FUNC_PING        2211
#define DRV_IOCTL_FUNC_WRITE       2212
#define DRV_IOCTL_FUNC_GET_PEB     2213

#define DRV_PING_MAGIC 0xD218097F004F73A4ULL

#define DRV_DEVICE_SUFFIX_W   L"LzxRCvwgqKap"
#define DRV_USER_DEVICE_PATH  L"\\\\.\\LzxRCvwgqKap"
#define DRV_KERNEL_DRIVER_OBJ L"\\Driver\\LzxRCvwgqKap"
#define DRV_KERNEL_DEVICE     L"\\Device\\LzxRCvwgqKap"
#define DRV_KERNEL_SYMLINK    L"\\DosDevices\\LzxRCvwgqKap"

#define DRV_SYS_FILE_NAME     L"LzxRCvwgqKap.sys"
#define DRV_MAPPER_EXE_NAME   L"hLAPbjrYxp.exe"
#define DRV_HOST_EXE_NAME     L"xYBxGUhizX.exe"
