param(
    [Parameter(Mandatory = $true)][string]$ReleaseDir,
    [Parameter(Mandatory = $true)][string]$LogoPath,
    [Parameter(Mandatory = $true)][string]$OutCpp
)

$ErrorActionPreference = 'Stop'

function Write-ByteArrayCppStream {
    param([byte[]]$Bytes, [string]$Symbol, [System.IO.StreamWriter]$Writer)
    $Writer.WriteLine("alignas(8) static const unsigned char $Symbol[] = {")
    for ($i = 0; $i -lt $Bytes.Length; $i++) {
        if (($i % 16) -eq 0) { $Writer.Write('    ') }
        $Writer.Write(('0x{0:X2},' -f $Bytes[$i]))
        if (($i % 16) -eq 15) { $Writer.WriteLine('') }
    }
    if (($Bytes.Length % 16) -ne 0) { $Writer.WriteLine('') }
    $Writer.WriteLine('};')
    $Writer.WriteLine("static const std::size_t ${Symbol}_size = $($Bytes.Length);")
}

function Should-PackFile {
    param([string]$Rel)
    $r = $Rel.Replace('\', '/').ToLowerInvariant()
    if ($r -match '(^|/)meshes/') { return $false }
    if ($r -match '\.(pdb|ilk|exp|lib|tlog|log|recipe)$') { return $false }
    if ($r -match 'crymore_loader\.exe$') { return $false }
    if ($r -match '^assets/') { return $true }
    if ($r -match '\.(exe|dll|sys|txt|jpeg|jpg|png|json|tri)$') { return $true }
    return $false
}

function Build-ArchiveBytes {
    param([string]$Root)
    $ms = New-Object System.IO.MemoryStream
    $writer = New-Object System.IO.BinaryWriter($ms)
    $writer.Write([UInt32]0x474D5243) # CRMG
    $writer.Write([UInt32]1)

    $files = @()
    if (Test-Path $Root) {
        $files = Get-ChildItem -Path $Root -Recurse -File |
            Where-Object { Should-PackFile $_.FullName.Substring($Root.Length).TrimStart('\', '/') } |
            Sort-Object FullName
    }
    $writer.Write([UInt32]$files.Count)

    foreach ($f in $files) {
        $rel = $f.FullName.Substring($Root.Length).TrimStart('\', '/').Replace('\', '/')
        $nameBytes = [System.Text.Encoding]::UTF8.GetBytes($rel)
        $data = [IO.File]::ReadAllBytes($f.FullName)
        $writer.Write([UInt32]$nameBytes.Length)
        $writer.Write($nameBytes, 0, $nameBytes.Length)
        $writer.Write([UInt32]$data.Length)
        $writer.Write($data, 0, $data.Length)
    }

    $writer.Flush()
    return $ms.ToArray()
}

if (-not (Test-Path $ReleaseDir)) {
    Write-Host "Release dir missing: $ReleaseDir"
    $archive = [byte[]]@(0x43,0x52,0x4D,0x47,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00)
} else {
    $archive = Build-ArchiveBytes -Root $ReleaseDir
    Write-Host "Packed $($archive.Length) bytes from $ReleaseDir"
}

$logoBytes = @()
if (Test-Path $LogoPath) {
    $logoBytes = [IO.File]::ReadAllBytes($LogoPath)
}

$outDir = Split-Path -Parent $OutCpp
if ($outDir -and -not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$sw = New-Object System.IO.StreamWriter($OutCpp, $false, [System.Text.UTF8Encoding]::new($false))
try {
    $sw.WriteLine('// Auto-generated by loader/tools/build_embedded_payload.ps1')
    $sw.WriteLine('#pragma once')
    $sw.WriteLine('#include <cstddef>')
    $sw.WriteLine('namespace loader_embed {')
    Write-ByteArrayCppStream -Bytes $archive -Symbol 'kPayloadArchive' -Writer $sw
    Write-ByteArrayCppStream -Bytes $logoBytes -Symbol 'kBrandLogoPng' -Writer $sw
    $sw.WriteLine('} // namespace loader_embed')
} finally {
    $sw.Close()
}

Write-Host "Wrote $OutCpp (payload=$($archive.Length) bytes, logo=$($logoBytes.Length) bytes)"
