param(
    [string]$RepoRoot = "",
    [string]$Version = ""
)

$ErrorActionPreference = "Stop"

if (-not $RepoRoot) {
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
}

$versionFile = Join-Path $RepoRoot "web\VERSION"
if (-not $Version) {
    if (Test-Path $versionFile) {
        $Version = (Get-Content $versionFile -Raw).Trim()
    } else {
        $Version = "0.0.0-dev"
    }
}

$gitSha = "unknown"
try {
    $sha = (& git -C $RepoRoot rev-parse --short=10 HEAD 2>$null)
    if ($LASTEXITCODE -eq 0 -and $sha) {
        $gitSha = $sha.Trim()
    }
} catch {
}

$buildUtc = [DateTimeOffset]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ")
$genDir = Join-Path $RepoRoot "generated"
New-Item -ItemType Directory -Force -Path $genDir | Out-Null

$headerPath = Join-Path $genDir "build_version.h"
$csPath = Join-Path $genDir "BuildInfo.g.cs"
$txtPath = Join-Path $genDir "version.txt"

@"
#pragma once

#define CRYMORE_VERSION "$Version"
#define CRYMORE_GIT_SHA "$gitSha"
#define CRYMORE_BUILD_UTC "$buildUtc"

namespace crymore_build {
inline constexpr const char* kVersion = CRYMORE_VERSION;
inline constexpr const char* kGitSha = CRYMORE_GIT_SHA;
inline constexpr const char* kBuildUtc = CRYMORE_BUILD_UTC;
}
"@ | Set-Content -Path $headerPath -Encoding ASCII

@"
// <auto-generated />
namespace Crymore.Loader;

internal static class BuildInfo
{
    public const string Version = "$Version";
    public const string GitSha = "$gitSha";
    public const string BuildUtc = "$buildUtc";
    public const string Display = "v$Version ($gitSha)";
}
"@ | Set-Content -Path $csPath -Encoding UTF8

@"
version=$Version
git=$gitSha
built_utc=$buildUtc
"@ | Set-Content -Path $txtPath -Encoding ASCII

Write-Host "==> Build version: v$Version ($gitSha) $buildUtc"
